<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/font.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/swiper.min.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/magnific-popup.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/layers.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/navigation.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/settings.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/range.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/nice-select.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/css/style.css">